name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Install conftest
      run: CGO_ENABLED=0 go install github.com/open-policy-agent/conftest@latest

    - name: Clone OPA policy sample
      run: |
        mkdir /tmp/sample
        cd /tmp/sample
        git clone https://github.com/lonegunmanb2/opa_policy_sample.git

    - name: Run tests
      run: |
        export POLICY_DIR="/tmp/sample/opa_policy_sample/policy-as-code/OPA/policy"
        export UTILS_REGO="/tmp/sample/opa_policy_sample/policy-as-code/OPA/policy/common.utils.rego"
        go test -v github.com/lonegunmanb/avmpolicytester/...